apiVersion : apps/v1
kind: Deployment
metadata:
  name: bunnydockk 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bunnydockk
  template:
    metadata:
      labels:
        app: bunnydockk 
    spec:
      containers:
        - name: bunnydockk 
          image: waregistryname.azurecr.io/bunnydockk
          ports:
          - containerPort: 80